@startuml
left to right direction
Title Use Case Diagram

actor Employee <<Logged in>>
actor Customer

rectangle System {
  Customer -- (Lav forespørgsel)
  (Lav forespørgsel) .> (Register / Login) : include
  Customer -- (Se godkente forespørgelser)
  (Se godkente forespørgelser) .> (Login) : include
  Customer -- (Modtag tilbud)
  (Modtag tilbud) .> (Login) : include
  Customer -- (Modtag stykliste)
  Customer -- (Modtag samlevejledning)

  Employee -- (Håndter forespørgseler)
  Employee -- (Håndter tilbud)
  Employee -- (Redigere matrialer)
  Employee -- (Se oversigt over brugere)
  Employee -- (Generere stykliste)

}
@enduml