GET http://localhost:8080/getRequests_war_exploded/api/customer/3

###

POST http://localhost:8080/getRequests_war_exploded/api/customer
Content-Type: application/json

{
  "firstName": "Karl",
  "lastName": "Johansen"
}

###

GET http://localhost:8080/getRequests_war_exploded/api/customer/all

###

DELETE http://localhost:8080/getRequests_war_exploded/api/customer/1

