@startuml
Title Navigationsdiagram Employee

state index.jsp
[*] --> index.jsp

state loginpage.jsp
index.jsp --> loginpage.jsp : User pressed login

state userpage.jsp
loginpage.jsp --> userpage.jsp : Succesfull login
index.jsp --> userpage.jsp : User pressed Profile button

state errorpage.jsp
loginpage.jsp --> errorpage.jsp : Failed login

userpage.jsp --> index.jsp : User pressed Home button

state users.jsp
index.jsp --> users.jsp : User pressed user button
users.jsp --> userpage.jsp : User pressed View User button

state customerorders.jsp
index.jsp --> customerorders.jsp : User pressed Orders button

state customerorderspecific.jsp
customerorders.jsp --> customerorderspecific.jsp : User pressed View Order button


@enduml